apiVersion: apps/v1
kind: Deployment
metadata:
  name: mybackend
  namespace: keycloak 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mybackend
  template:
    metadata:
      labels:
        app: mybackend
    spec:
      containers:
        - name: mybackend
          image: cprajwowski/backend
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          env:
            - name: KEYCLOAK_HOST_URL
              value: "http://keycloak-service:8080"
          livenessProbe:
            httpGet:
              path: /post
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /post
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: mybackend
  namespace: keycloak
spec:
  selector:
    app: mybackend
  ports:
    - protocol: TCP
      port: 8000  
      targetPort: 8000
  type: NodePort