apiVersion: apps/v1
kind: Deployment
metadata:
  name: mymongo
  namespace: keycloak 
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: mymongo
  template:
    metadata:
      labels:
        app: mymongo
    spec:
      containers:
        - name: mymongo
          image: cprajwowski/mymongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secrets
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secrets
                  key: MONGO_INITDB_ROOT_PASSWORD
          ports:
            - containerPort: 27017

---

apiVersion: v1
kind: Service
metadata:
  name: mymongo
  namespace: keycloak
spec:
  selector:
    app: mymongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017  
  type: ClusterIP
