apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: keycloak
type: Opaque
data:
  KEYCLOAK_ADMIN: YWRtaW4=
  KEYCLOAK_ADMIN_PASSWORD: YWRtaW4=
  KC_DB_USERNAME: a2V5Y2xvYWs=
  KC_DB_PASSWORD: cGFzc3dvcmQ=
  POSTGRES_PASSWORD: cGFzc3dvcmQ= 

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-configmap
  namespace: keycloak
data:
  KC_DB_URL_PORT: "5432"
  KC_DB_URL_HOST: postgres-service
  KC_DB: postgres
  POSTGRES_DB: keycloak
  POSTGRES_USER: keycloak