apiVersion: apps/v1
kind: Deployment
metadata:
  name: myreact
  namespace: keycloak
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: myreact
  template:
    metadata:
      labels:
        app: myreact
    spec:
      containers:
        - name: myreact
          image: cprajwowski/react
          ports:
            - containerPort: 3000  

---           
apiVersion: v1
kind: Service
metadata:
  name: myreact
  namespace: keycloak
spec:
  selector:
    app: myreact
  ports:
    - protocol: TCP
      port: 3000  
      targetPort: 3000  
  type: LoadBalancer