apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\PRA\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: mymongo
  name: mymongo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mymongo
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\PRA\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/komposem-mynetwork: "true"
        io.kompose.service: mymongo
    spec:
      containers:
        - image: cprajwowski/mymongo
          name: mymongo
          resources: {}
      restartPolicy: Always
status: {}
